project 'CodeApp.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CodeApp
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYKit', '~> 1.0.9'

  target 'CodeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
